### ISSUE TITLE
Ionic serve stuck with lot of errors

### ISSUE THREAD

**Issue by rodrigoreal** [aaronksaunders/ionic2-angularfire-sample#1]
I just download your project and did all the configuration steps, but i can't run the project.
When i type "ionic serve" i get a lot of errors and it get stuck, the project don't even start in my browser.

Do you have any idea why it is happening? Thanks
<img width="1280" alt="captura de tela 2016-05-13 as 00 18 54" src="https://cloud.githubusercontent.com/assets/8595202/15237009/862b6ade-18a0-11e6-9d1b-b5cc129fdad8.png">

```
Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.6
Ionic CLI Version: 2.0.0-beta.25
Ionic App Lib Version: 2.0.0-beta.15
ios-deploy version: 1.8.5
ios-sim version: 5.0.8
OS: Mac OS X El Capitan
Node Version: v5.6.0
Xcode version: Xcode 7.3.1 Build version 7D1014
```

**Comment by aaronksaunders** [comment]
did you do an npm install after downloading the project... did you load the typings? and which tag are you using part1 or the head?

**Comment by rodrigoreal** [comment]
@aaronksaunders yea, i did an npm install and im using the head..
What you mean by load the typings? I don't see any step about typings in the configuration step.

I just downloaded the project from the head, did an npm install and then ionic serve.

**Comment by rodrigoreal** [comment]
Ok its seen to be a ionic problem because they are not using Angular 2.0.0-rc yet
https://github.com/driftyco/ionic/issues/6493

Thanks anyway

**Comment by aaronksaunders** [comment]
You can also always rollback to an older version of angular fire to start the development
