### ISSUE TITLE
Doesn't fix latest Angular2/Firebase problems

### ISSUE THREAD

**Issue by locohost** [aaronksaunders/ionic2-angularfire-sample#12]
After finding this today, I had hopes, but sadly same AF2/Firebase problems...

I cloned this project, changed nothing,  then did npm install and got...

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installe
d.

**Comment by jose2007kj** [comment]
warnings are not an issue....its ok

**Comment by locohost** [comment]
@jose2007kj I do get errors when Ionic tries to build. The errors are about these warnings.

**Comment by aaronksaunders** [comment]
looks like you are have other issue based on your warnings... delete your `node_modules` directory and run `npm install` again

**Comment by locohost** [comment]
@aaronksaunders Thanks for helping. I really appreciate it. I've deleted my global npm once to be sure that was clean of any old versions. I've cleared/cleaned the project local cache and node_modules folder many, many times. I'm doing that each time I npm install new versions of software and new package.json settings.

Could it be this is working for you due to specific software already installed in your global npm node_modules?

I will clear the global npm (so it's a known state) and local cache and delete the node_modules again as is my practice before I match my package.json to your image.

Thank you Aaron! :-)

**Comment by locohost** [comment]
Ok... I'm happy to say this went a lot better. 

My steps just now were...

--- Clear global npm cache user/myusername/appdata/roaming/npm (delete this folder)
--- NOTE: This is global so only have to do this once
npm install -g npm
npm install --global --production windows-build-tools
npm install -g minimatch@3.0.2 lodash graceful-fs

--- Run cmd as Admin
--- In cmd in project folder: clear local cache and node_modules folder
npm cache clear & npm cache clean & rmdir /s /q node_modules

Edit my package.json dependancies to match above image

npm install

I got this after install, which looks better than anything I've seen so far...

...
...
| +-- once@1.3.3
| +-- optimist@0.6.1
| +-- path-is-absolute@1.0.0
| +-- resolve@1.1.7
| +-- sprintf-js@1.0.3
| +-- tslint@3.10.2
| +-- tslint-eslint-rules@1.3.0
| +-- underscore.string@3.3.4
| +-- util-deprecate@1.0.2
| +-- wordwrap@0.0.3
| `-- wrappy@1.0.2
`-- zone.js@0.6.12

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.

@aaronksaunders Do you see any problem with above npm install output? I'll try to run the app when I get home this evening.

**Comment by aaronksaunders** [comment]
@locohost i have a windows machine that i can test this on, I usually work on a mac... also I am running windows10. I will let you know what my results are

**Comment by aaronksaunders** [comment]
just tested this on my windows machine and it works fine
```
Cordova CLI: 6.3.1  
Gulp local:   Local version 3.9.1                                                                         
Ionic Framework Version: 2.0.0-beta.11                                                                    
Ionic CLI Version: 2.0.0                                                                                  
Ionic App Lib Version: 2.0.0-beta.20                                                                      
OS:                                                                                                       
Node Version: v4.4.1         
```

**Comment by locohost** [comment]
@aaronksaunders Ok Aaron you got me through this. It's working. You are a gentleman and a scholar :-) This Ionic2/AngularFire2/Firebase project setup is all _extraordinarily_ difficult to make work. Is due to Ionic2 being beta?

**Comment by aaronksaunders** [comment]
I don't know why people are rushing to use angularfire, at this point just using the JavaScript library is sufficient and way less complex. 

We have deployed 3 apps for clients using ionic2 and firebase3 with no issues and no angularfire.

**Comment by locohost** [comment]
Ok I'm intrigued. Do you have an example using Ionic2/Firebase3 without
AF2? Are you speaking of building REST service? I have a Node/Express
backend hooked my MongoDB replica set. Have you looked at Back&? What do
you think about that?

**Comment by aaronksaunders** [comment]
@locohost see https://github.com/aaronksaunders/firebaseStorage2
