### ISSUE TITLE
Not redirecting to home page after login

### ISSUE THREAD

**Issue by AhsanAyaz** [aaronksaunders/ionic2-angularfire-sample#2]
auth.subscribe is not being triggered on login while being triggered on logout.
:disappointed:

**Comment by aaronksaunders** [comment]
@AhsanAyaz can you provide some code?

**Comment by zefrench** [comment]
Yes, thats true it seems after the login success, the modal is dismiss but the home.html stays blank.
It seems the variable auth is not reflected in the line : `<div *ngIf="auth | async">You are logged in as {{authInfo && authInfo.displayName}}</div>`

**Comment by zefrench** [comment]
Ashen, did you find a way to fix it ?

**Comment by aaronksaunders** [comment]
can you provide some sample code so I can look into your issue? Also please provide output from `ionic info`

**Comment by shamrozwarraich** [comment]
yes @AhsanAyaz  @zefrench  `auth.subscribe ` not working
  hey @aaronksaunders 
user login and created successfully but when in home as u use in ngOnInt function 
`
    alert("OnInit")
    this.af.auth.subscribe(data =>{
      if(data){
         alert((Success);
     }
)
`
when the home page reload ans the control goes to OniNit function just 1st alert OnInit is show on device the control not going inside the subsribe the user login....one more, using ng serve all work fine but in real device not working why why,,,  ;/
 ionic beta 11, rc4 .. angularfire2 beta 2.

**Comment by AhsanAyaz** [comment]
I haven't been able to fix this yet because I was busy on another project. Will look into it more. And yes @shamrozwarraich, @zefrench you're right. I'll dig into this soon.

**Comment by aaronksaunders** [comment]
in the middle of getting a client release out... will try and upgrade to the latest of everything and get this functional

**Comment by aaronksaunders** [comment]
i have commited a build that I have updated to the latest Ionic and the latest firebase and angularFire.

there is a bug in ionic with modals that forced me to hack in the Angulafire DI, I will log an issue when I get a chance
