### ISSUE TITLE
error error error :/

### ISSUE THREAD

**Issue by shamrozwarraich** [aaronksaunders/ionic2-angularfire-sample#4]
plz help 
clone your project ...
When attempting to use the AngularFire2 guide in ionic beta facing the cli error .....
also include "files" array in the tsconfig.json file.
"files": [
"node_modules/angularfire2/firebase3.d.ts"
],

E:\firebase v3\ionic2-angularfire-sample>ionic serve
`
Running 'serve:before' gulp task before serve
..............

TypeScript error: E:/firebase v3/ionic2-angularfire-sample/app/pages/home/home.t
s(42,47): Error TS2339: Property 'displayName' does not exist on type 'TwitterCr
edential'.
TypeScript error: E:/firebase v3/ionic2-angularfire-sample/node_modules/angularf
ire2/database/database.d.ts(10,31): Error TS2503: Cannot find namespace 'firebas
e'.

TypeScript error: app/app.ts(18,25): Error TS2345: Argument of type 'string' is
not assignable to parameter of type 'FirebaseAppConfig'.
[01:28:03] Finished 'watch' after 32 s
[01:28:03] Starting 'serve:before'...
[01:28:03] Finished 'serve:before' after 21 μs

Running live reload server: http://localhost:35729
Watching: www//*, !www/lib//*
√ Running dev server: http://localhost:8100
Ionic server commands, enter:
restart or r to restart the client app from the root
goto or g and a url to have the app navigate to the given url
consolelogs or c to enable/disable console log output
serverlogs or s to enable/disable server log output
quit or q to shutdown the server and exit

ionic $ 10.5 MB bytes written (37.19 seconds)
TypeScript error: E:/firebase v3/ionic2-angularfire-sample/app/pages/home/home.t
s(42,47): Error TS2339: Property 'displayName' does not exist on type 'TwitterCr
edential'.
TypeScript error: E:/firebase v3/ionic2-angularfire-sample/node_modules/angularf
ire2/database/database.d.ts(9,29): Error TS2503: Cannot find namespace 'firebase
'.......

TypeScript error: app/app.ts(18,25): Error TS2345: Argument of type 'string' is
not assignable to parameter of type 'FirebaseAppConfig'.
10.5 MB bytes written (3.66 seconds)

firebase v3\ionic2-angularfire-sample>typings install --save --ambient firebase
typings ERR! deprecated The "ambient" flag is deprecated. Please use "global" in
stead

E:\firebase v3\ionic2-angularfire-sample>typings install --save --global dt~fire
base
firebase
└── (No dependencies)_
)

**Comment by aaronksaunders** [comment]
i havent had a chance to circle back to this.... also it looks like you are not on the v3 branch

https://github.com/aaronksaunders/ionic2-angularfire-sample/tree/firebase3-support

There is a less complex example here to get you started
https://github.com/aaronksaunders/AngularFire2-Ionic2-Facebook

**Comment by aaronksaunders** [comment]
please try the latest code, I have updated to latest Firebase and Ionic
